// Import AST Node Classes
import {
    FunctionCall,
    Comparison,
    ValueNode,
} from './grammar.js';  // Adjust the path as necessary
import ast from "./grammar.js"; // Importing the AST generated by the parser

// Define the Interpreter class
class Interpreter {
    constructor(ast, inputString) {
        this.ast = ast;
        this.inputString = inputString;
    }

    interpret() {
        console.log(this.ast);
        return this.evaluate(this.ast);
    }

    evaluate(node) {
        if (node instanceof FunctionCall) {
            return this.evaluateFunctionCall(node);
        } else if (node instanceof Comparison) {
            return this.evaluateComparison(node);
        } else if (node instanceof ValueNode) {
            return this.evaluateValueNode(node);
        } else {
            throw new Error(`Unexpected node type: ${node.constructor.name}`);
        }
    }

    evaluateFunctionCall(node) {
        const functionName = node.name;
        const args = node.args.map(arg => this.evaluate(arg)); // Evaluate each argument
        console.log(`Function: ${functionName}, Args: ${args}`);

        if (functionName === 'count') {
            return this.count(args[0]);
        } else if (functionName === 'sum') {
            return this.sum(args[0]);
        } else if (functionName === 'max') {
            return this.max(args);
        } else {
            throw new Error(`Unknown function: ${functionName}`);
        }
    }

    evaluateComparison(node) {
        const left = this.evaluate(node.left);
        const right = this.evaluate(node.right);
        const operator = node.operator;

        switch (operator) {
            case '>':
                return left > right;
            case '>=':
                return left >= right;
            case '<':
                return left < right;
            case '==':
                return left === right;
            case '+':
                return left + right;
            case '*':
                return left * right;
            case '-':
                return left - right;
            default:
                throw new Error(`Unknown operator: ${operator}`);
        }
    }

    evaluateValueNode(node) {
        return node.value;
    }

    // Implementations of count, sum, and max functions
    count(arg) {
        const str = this.inputString;
        let cnt = 0;
        const characters = str.split("");
        characters.forEach((character) => {
            if (character == arg) cnt++;
        });
        return cnt;
    }

    sum(arg) {
        const regex = new RegExp(arg, 'g');
        let total = 0;
        let match;
        while ((match = regex.exec(this.inputString)) !== null) {
            total += parseInt(match[0], 10);
        }
        return total;
    }

    max(args) {
        return Math.max(...args);
    }
}

const inputString = "aaaabb123cca456";
const interpreter = new Interpreter(ast, inputString);
const result = interpreter.interpret();
console.log(result); // Output the result of the interpretation

export default result;
